export const LOGIN = 'AUTH/LOGIN'
export const LOGIN_PENDING = 'AUTH/LOGIN_PENDING'
export const LOGIN_FAILURE = 'AUTH/LOGIN_FAILURE'

export const LOGOUT = 'AUTH/LOGOUT'
export const INITIALIZE = 'AUTH/INITIALIZE_SESSION'
export const SET_REDIRECT_AFTER_LOGIN = 'AUTH/SET_REDIRECT_AFTER_LOGIN'
